name: trna
channels:
  - conda-forge
  - bioconda
  - defaults
  - biobuilds
dependencies:
  - python=3.10
  - shrimp=2.2.3
  - samtools=1.18
  - pysamstats=1.1.2
  - pysam=0.21.0
  - gmap=2023.10.10
  - pandas=2.1.2
  - biopython=1.81
  - bowtie2=2.5.2
  - bwa=0.7.17
  - numpy=1.26.0
  - scipy=1.11.3
  - ca-certificates=2023.7.22
  - certifi=2023.7.22
  - openssl=3.1.4
  - clustalw=2.1
  - cgatcore=0.6.15
  - salmon=0.8.1
  - tbb=2021.10.0
  - networkx=3.2.1
