# Name of default conda environment for all tasks
conda_base_env: 'trna'

# Directory for input files
input: './input'

# pipeline expects file in the format used by mimseq, e.g
# https://github.com/nedialkova-lab/mim-tRNAseq/blob/master/mimseq/data/hg38-eColitK/hg38-tRNAs-filtered.fa
# must end in .fa
# Need to add back the sequence (not name!) for
# >Homo_sapiens_tRNA-Cys-GCA-19-1 (tRNAscan-SE ID: chr7.trna22) Cys (GCA) 72 bp Sc: 69.2 chr7:149613064-149613136(-)
# GGGGGTATAGCTCAGGGGTAGAGCATTTGACTGCAAATCAAGAGGTCCCTGATTCAAATCCAGGTGCCCCCT
# which seems to have got removed!
trna_sequences_infile: './hg38-tRNAs-filtered.fa'

# https://github.com/nedialkova-lab/mim-tRNAseq/blob/master/build/lib/mimseq/data/hg38-eColitK/hg38-mitotRNAs.fa
trna_mt_sequences_infile: './hg38-mitotRNAs.fa'

# tRNAscan-SE .out file
#https://raw.githubusercontent.com/nedialkova-lab/mim-tRNAseq/master/mimseq/data/hg38-eColitK/hg38-tRNAs-detailed.out
trna_scan_infile: './hg38-tRNAs-detailed.out'

# Obtained from https://genesilico.pl/modomics/modifications -> CSV
modification_index: 'index.csv'

# Obtained from e.g https://www.genesilico.pl/modomics/api/sequences?RNAtype=tRNA&organism=Homo+sapiens&format=json
modomics_json: sequences.json


simulation:

  # How many iterations per simulation (note that uniform is only done once)
  n: 2

  # Uniform (same counts per tRNA sequence) simulation
  uniform_reads: 1000000
  withmut_reads: 1000000

mimseq:
  threads: 7
  conda_env_name: 'mimseq'
  # maximum number of simultaneous tasks. Use 1 if running locally to avoid excessive CPU usage!
  max_sim_tasks: 100

shrimp:
  threads: 1

bowtie2:
  threads: 1
  d_values: '10,20,30,40,50,60,70,80,90,100'
  l_values: '10,12,14,16,18,20'
  n_values: '0,1'
bwamem:
  threads: 1
  k_values: '7,9,11,13,15,19'
  r_values: '1,1.1,1.2,1.3,1.4,1.5'